const WORD_HINTS: Record<string, string> = {
  aa: 'rough lava',
  ab: 'abdominal muscle',
  ad: 'advertisement',
  ae: 'one (Scottish)',
  ag: 'agriculture; silver',
  ah: 'exclamation of surprise',
  ai: 'three-toed sloth',
  al: 'East Indian tree',
  am: 'form of “be”',
  an: 'indefinite article',
  ar: 'the letter R',
  as: 'to the same degree',
  at: 'in a location',
  aw: 'expression of sympathy',
  ax: 'cutting tool',
  ay: 'yes; ever',
  ba: 'Egyptian soul',
  be: 'to exist',
  bi: 'bisexual',
  bo: 'pal; friend',
  by: 'near; via',
  de: 'of; from',
  do: 'perform; a tone',
  ed: 'education; editor',
  ef: 'the letter F',
  eh: 'expression of doubt',
  el: 'elevated railway; the letter L',
  em: 'the letter M; a print measure',
  en: 'the letter N; a print measure',
  er: 'hesitation sound',
  es: 'the letter S',
  et: 'past of eat (dialect)',
  ex: 'former partner; the letter X',
  fa: 'a musical tone',
  fe: 'Hebrew letter',
  gi: 'martial-arts uniform',
  go: 'to move; a board game',
  ha: 'laugh sound',
  he: 'male pronoun',
  hi: 'greeting',
  hm: 'thoughtful sound',
  ho: 'attention call',
  id: 'instinctual mind',
  if: 'on the condition',
  in: 'inside',
  is: 'form of “be”',
  it: 'neuter pronoun',
  jo: 'sweetheart',
  ka: 'Egyptian spirit',
  ki: 'vital energy; variant of qi',
  la: 'a musical tone',
  li: 'Chinese distance unit',
  lo: 'look; behold',
  ma: 'mother',
  me: 'objective “I”',
  mi: 'a musical tone',
  mm: 'agreement sound',
  mo: 'moment; Missouri',
  mu: 'Greek letter',
  my: 'belonging to me',
  na: 'no; sodium',
  ne: 'born as (née)',
  no: 'negative; Japanese drama',
  nu: 'Greek letter',
  od: 'hypothetical force',
  oe: 'Faroe Islands whirlwind',
  of: 'belonging to',
  oh: 'exclamation',
  oi: 'hey; a shout',
  ok: 'all right',
  om: 'mantra syllable',
  on: 'in contact with',
  op: 'operation; optical art',
  or: 'alternatively; gold in heraldry',
  os: 'bone; a mouth',
  ow: 'pain exclamation',
  ox: 'bovine animal',
  oy: 'exclamation of dismay',
  pa: 'father',
  pe: 'Hebrew letter',
  pi: 'Greek letter; 3.14159…',
  qat: 'evergreen shrub; stimulant leaf',
  qi: 'vital energy in Chinese thought',
  re: 'regarding; a musical tone',
  sh: 'be quiet',
  si: 'a musical tone; yes (Spanish/Italian)',
  so: 'therefore; a musical tone',
  suq: 'open-air market',
  ta: 'thanks',
  ti: 'a musical tone',
  to: 'toward',
  uh: 'hesitation sound',
  um: 'hesitation sound',
  un: 'one (dialect); a prefix',
  up: 'to a higher place',
  us: 'objective “we”',
  ut: 'old musical tone',
  we: 'first-person plural',
  wo: 'woe',
  xi: 'Greek letter',
  xu: 'Vietnamese coin',
  ya: 'you (dialect)',
  ye: 'you (archaic)',
  yo: 'greeting',
  za: 'pizza (slang)',
  zo: 'Tibetan cattle breed',
};

export function getWordHint(word: string): string | null {
  const key = word.trim().toLowerCase();
  return WORD_HINTS[key] ?? null;
}

export function getWordLookupHref(word: string): string {
  return `https://en.wiktionary.org/wiki/${encodeURIComponent(word.trim().toLowerCase())}`;
}
